/* Generated by Yosys 0.7+156 (git sha1 92a77e2, gcc 6.3.1 -fPIC -Os) */

(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:6" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "counter.v:3" *)
  input clk;
  (* src = "counter.v:4" *)
  output [2:0] count;
  (* src = "counter.v:3" *)
  input en;
  (* src = "counter.v:3" *)
  input rst;
  NOT _14_ (
    .A(count[1]),
    .Y(_13_)
  );
  NOT _15_ (
    .A(rst),
    .Y(_01_)
  );
  NAND _16_ (
    .A(en),
    .B(count[0]),
    .Y(_02_)
  );
  NOR _17_ (
    .A(en),
    .B(count[0]),
    .Y(_03_)
  );
  NOR _18_ (
    .A(rst),
    .B(_03_),
    .Y(_04_)
  );
  NAND _19_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  NOT _20_ (
    .A(_05_),
    .Y(_00_[0])
  );
  NOR _21_ (
    .A(_13_),
    .B(_02_),
    .Y(_06_)
  );
  NAND _22_ (
    .A(_13_),
    .B(_02_),
    .Y(_07_)
  );
  NAND _23_ (
    .A(_01_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _24_ (
    .A(_06_),
    .B(_08_),
    .Y(_00_[1])
  );
  NAND _25_ (
    .A(count[2]),
    .B(_06_),
    .Y(_09_)
  );
  NOR _26_ (
    .A(count[2]),
    .B(_06_),
    .Y(_10_)
  );
  NOT _27_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _28_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _29_ (
    .A(rst),
    .B(_12_),
    .Y(_00_[2])
  );
  DFF _30_ (
    .C(clk),
    .D(_00_[0]),
    .Q(count[0])
  );
  DFF _31_ (
    .C(clk),
    .D(_00_[1]),
    .Q(count[1])
  );
  DFF _32_ (
    .C(clk),
    .D(_00_[2]),
    .Q(count[2])
  );
endmodule
